
- name: docker playbook
  hosts: all
  gather_facts: false

  tasks:

        
    - name: Deploy stack
      community.docker.docker_stack:
        state: present
        name: alfstack
        compose:
          - version: '3'
            services:
              share:
                image: docker.io/alfresco/alfresco-governance-share-community:7.4.0-M3
                deploy:
                  placement:
                    constraints:
                      - "{{ item }}"
                environment:
                  REPO_HOST: "alfresco"
                  REPO_PORT: "8080"
                  JAVA_OPTS: >-
                    -XX:MinRAMPercentage=50
                    -XX:MaxRAMPercentage=80
                    -Dalfresco.host=localhost
                    -Dalfresco.port=8080
                    -Dalfresco.context=alfresco
                    -Dalfresco.protocol=http
      loop:
        "{{ LABELS }}"