---
- name: Check Docker Image Availability
  hosts: localhost
  vars:
    image_namespace: 
    image_name: portal
    image_version: 1 #'{{ REPOSITORY_VERSION }}'
    stack_name: igsstack
  tasks:
    - name: Deploy stack
      community.docker.docker_stack:
        state: present
        name: newstack
        compose:
          - version: '3'
            services:
              postgres:
                image: postgres:14.4
                deploy:
                  placement:
                    constraints:
                      - node.labels.isNfsClient==true
                deploy:
                  placement:
                    constraints:
                      - node.labels.isNfsClient==true
                environment:
                  - POSTGRES_PASSWORD=alfresco
                  - POSTGRES_USER=alfresco
                  - POSTGRES_DB=alfresco
                command: postgres -c max_connections=300 -c log_min_messages=LOG
                ports:
                  - "5432:5432"
              