

- name: docker playbook
  hosts: all
  gather_facts: true

  tasks:
        
    - name: Deploy stack
      community.docker.docker_stack:
        state: present
        name: alfstack
        compose:
          - version: '3'
            services:
              solr6:
                image: docker.io/alfresco/alfresco-search-services:2.0.6
                deploy:
                  placement:
                    constraints:
                      - "{{ item }}"
                environment:
                  # Solr needs to know how to register itself with Alfresco
                  SOLR_ALFRESCO_HOST: "alfresco"
                  SOLR_ALFRESCO_PORT: "8080"
                  # Alfresco needs to know how to call solr
                  SOLR_SOLR_HOST: "solr6"
                  SOLR_SOLR_PORT: "8983"
                  # Create the default alfresco and archive cores
                  SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
                  # HTTPS or SECRET
                  ALFRESCO_SECURE_COMMS: "secret"
                  # SHARED SECRET VALUE
                  JAVA_TOOL_OPTIONS: >-
                    -Dalfresco.secureComms.secret=secret
                ports:
                  - "8083:8983" # Browser port
                volumes:
                  - "{{ CLIENT_MNT_DIR }}/{{VOLUME_DIR}}:{{ CONTAINER_DATA_DIR }}"
    
      loop:
        "{{ LABELS }}"
              
