---
- name: add remote machine
  hosts: localhost
  become: yes
  vars:
      host_ip: "{{ ANSIBLE_HOST_IP }}"
  tasks:
    - name: Add targets 
      add_host:
        name: "{{ ANSIBLE_HOST_NAME }}"
        ansible_host: "{{ ANSIBLE_HOST_IP }}"
        ansible_user: "{{ ANSIBLE_USER }}"
      when: 
        - host_ip != "localhost"


    # - name: check the output to see if the hosts are added 
    #   debug:
    #     var: hostvars
- name: create
  hosts: 
    - "{{ ANSIBLE_HOST_NAME }}"
  gather_facts: true
  become: true
  become_method: sudo

  tasks:
    # - name: use this task to check if your os belong to the Debian family
    #   debug:
    #     msg: ansible_os_family == "{{ ansible_os_family }}"
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"


