- name: Run Tomcat Docker Container with Default Webapp
  hosts: all
  gather_facts: no
  # http://192.168.221.163:8080/docs
  vars:
    labels: '{{ LABELS }}'
  tasks:
          
    - name: Deploy stack - postgres
      community.docker.docker_stack:
        state: present
        name: igsstack
        compose:
          - version: '3'
            services:
              postgres:
                image: postgres:14.4
                environment:
                  POSTGRES_DB: igsdatabase
                  POSTGRES_USER: igs
                  POSTGRES_PASSWORD: igs
                ports:
                  - "5432:5432"
                deploy:
                  placement:
                    constraints:
                      - "{{ item }}"
      loop:
        "{{ labels }}"

