---
- name: add hosts to Ansible 
  hosts: localhost
  gather_facts: true  
  vars:
      host_ip: "{{ ANSIBLE_HOST_IP }}"
  tasks:
    - name: Add host 
      add_host:
        name: "{{ ANSIBLE_HOST_NAME }}"
        ansible_host: "{{ ANSIBLE_HOST_IP }}"
        ansible_user: "{{ ANSIBLE_USER }}"
      when: 
        - host_ip != "localhost"
        
    - name: Merge node labels and new labels
      community.docker.docker_node:
        hostname: "{{ HOST_NAME }}"
        labels:
          "{{ NODE_LABELS }}"
   

- name: Join target machines to Docker Swarm
  hosts: 
    - "{{ ANSIBLE_HOST_NAME }}"
  gather_facts: false
  become: true
  become_method: sudo
  vars:
    ansible_become_pass: "passw0rd"


  tasks:

    - name: change permission
      command: sudo chmod 666 /var/run/docker.sock

    ### THIS IMPLEMENTATION WILL BE DONE IN RELATHIONSHIP TYPE###
    # - name: Join worker to Docker Swarm
    #   community.docker.docker_swarm:
    #     state: join
    #     join_token: "{{ JOIN_TOKEN}}"
    #     remote_addrs: [ '{{MANAGER_IP}}:2377' ]
    #############################################################



    