---
- name: add remote machine
  hosts: localhost
  become: yes
  vars:
      host_ip: 129.69.209.200
  tasks:
    - name: Add targets 
      add_host:
        name: target_machine
        ansible_host: 129.69.209.200
        ansible_user: jingyue
      when: 
        - host_ip != "localhost"


    # - name: check the output to see if the hosts are added 
    #   debug:
    #     var: hostvars
- name: create
  hosts: 
    - target_machine
  gather_facts: true
  become: true
  become_method: sudo

 
    clientIPs:
      - 192.168.221.163
      - 192.168.221.133
  tasks:
    # - name: use this task to check if your os belong to the Debian family
    #   debug:
    #     msg: ansible_os_family == "{{ ansible_os_family }}"


    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: Install required packages
      apt:
        pkg:
          - nfs-kernel-server

      when: ansible_os_family == "Debian"

    - name: Create directory with equivalent of mkdir -p
      ansible.builtin.file:
        path: "/mnt/nfsdir"
        state: directory
        recurse: yes
        owner: nobody
        group: nogroup
        mode: '777'

   -  name: Add new Line
      ansible.builtin.lineinfile:
        state: present
        dest: /etc/exports
        line: "/mnt/nfsdir {{ item }}(rw,sync,no_subtree_check)"
        insertafter: EOF
      loop:
        "{{clientIPs}}"

          