- name: Run Tomcat Docker Container with igs repostiory Web application
  hosts: all
  gather_facts: no

  vars:
    image_namespace: igsrepo
    image_name: portal
    image_version: '{{ PORTAL_VERSION }}' # 1
    stack_name: igsstack
    labels: '{{ LABELS }}'
  tasks:
    - name: Deploy stack - repostiory
      community.docker.docker_stack:
        state: present
        name: igsstack
        compose:
          - version: '3'
            services:
              igsportal:
                image: '{{image_namespace}}/{{image_name}}:{{image_version}}' 
                deploy:
                  placement:
                    constraints:
                      - "{{ item }}"
      loop:
        "{{ labels }}"
