---
- name: Check PostgreSQL Connection
  hosts: localhost
  vars:
    postgres_host: localhost # service name
    postgres_port: 5432 
    postgres_db: igsdatabase
    postgres_user: igs
    postgres_password: igs
    log_file_loc: /home/ubuntu/opera-root/git-project/IGS_types/validation.log
  tasks:
    - name: install community general collection 
      shell: ansible-galaxy collection install community.general

    - name: Install packages for ansible 
      ansible.builtin.pip:
        name:
          - psycopg2-binary

    - name: Ping PostgreSQL Database
      community.general.postgresql_ping:
        db: "{{ postgres_db }}"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
      register: ping_output

    - name: write a banner
      delegate_to: localhost
      ansible.builtin.shell: echo "*********Validating Postgres Service on machine "{{ ansible_ssh_host }}"****{{ ansible_date_time.date }} {{ ansible_date_time.time }}*****" >> '{{log_file_loc}}'

    - name: if succeed, write msg back to a file in the controller node
      delegate_to: localhost
      ansible.builtin.shell: echo " Success! Postgres can be connected, version is {{ ping_output.server_version.full }}" >> '{{log_file_loc}}'
      when: ping_output.is_available 

    - name: if failed, write msg back to a file in the controller node
      delegate_to: localhost
      ansible.builtin.shell: echo " Failure! Postgres CANNOT be connected" >> '{{log_file_loc}}'
      when: not ping_output.is_available




