---

- name: docker playbook
  hosts: all
  gather_facts: true
  vars:
    log_file_loc: /home/ubuntu/opera-root/git-project/IGS_types/validation.log
  tasks:
    - name: get validating machines's ip
      set_fact:
        current_machine_ip: "{{ ansible_ssh_host }}"
    - name: write a banner
      delegate_to: localhost
      ansible.builtin.shell: echo "*********Validating Swarm Worker on machine {{current_machine_ip}}****{{ ansible_date_time.date }} {{ ansible_date_time.time }}*****" >> '{{log_file_loc}}'


    - name: execute docker info
      ansible.builtin.shell: docker info
      register: docker_info

    - name: check if swarm is active on this node
      set_fact:
        is_swarm_instance: "{{ 'Swarm: active' in docker_info.stdout }}"

    - name: if the node is NOT part of a Swarm, write msg back to a file in the controller node
      delegate_to: localhost
      ansible.builtin.shell: echo " Failure! This node is not a Swarm instance" >> '{{log_file_loc}}'
      when: not is_swarm_instance

    - name: Skip the rest tasks if not a Swarm instance
      ansible.builtin.meta: end_play
      when: not is_swarm_instance

    - name: check the Swarm role for this node
      set_fact:
        is_swarm_worker: "{{ 'Swarm: active' in docker_info.stdout and 'Is Manager: false' in docker_info.stdout }}"

    - name: if the node is Swarm worker, write msg back to a file in the controller node
      delegate_to: localhost
      ansible.builtin.shell: echo " Success! This node has been initialized as Swarm Worker" >> '{{log_file_loc}}'
      when: is_swarm_worker


    - name: if the node is NOT Swarm worker, write msg back to a file in the controller node
      delegate_to: localhost
      ansible.builtin.shell: echo " Failure! This node is NOT initialized as Swarm Worker" >> '{{log_file_loc}}'
      when: not is_swarm_worker