- name: Run Tomcat Docker Container with igs repostiory Web application
  hosts: all
  gather_facts: no

  tasks:
    - name: Build Docker Image
      community.docker.docker_image:
        name: igs-repository-spring
        source: build
        tag: latest
        build:
          path: "."
          
    - name: Deploy stack - repostiory
      community.docker.docker_stack:
        state: present
        name: igsstack
        compose:
          - version: '3'
            services:
              igsrepository:
                image: igs-repository-spring:latest
                ports:
                  - "8080:8080"
                ### dependency is expressed by Tosca ###
                # depends_on:
                #   - postgres
                ########################################

