version: '3'
services:

  igsrepository:
    image: igs-repository-spring:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: igsdatabase
      POSTGRES_USER: igs
      POSTGRES_PASSWORD: igs
    ports:
      - "5432:5432"

  igsportal:
    image: igs-portal-new:latest
    # ports:
    #   - "8081:8080"

  nginx:
    image: igs-proxy:latest
    ports:
      - "80:80"
    # volumes:
    #   - ./nginxconf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - igsrepository
      - igsportal