---
# - name: add remote machine
#   hosts: localhost
#   become: yes
#   vars:
#       host_ip: "{{ ANSIBLE_HOST_IP }}"
#   tasks:
#     - name: Add targets 
#       add_host:
#         name: "{{ ANSIBLE_HOST_NAME }}"
#         ansible_host: "{{ ANSIBLE_HOST_IP }}"
#         ansible_user: "{{ ANSIBLE_USER }}"
#       when: 
#         - host_ip != "localhost"


# - name: create
#   hosts: 
#     - "{{ ANSIBLE_HOST_NAME }}"
#   gather_facts: true
#   become: true
#   become_method: sudo
- name: add NFS export information on the server
  hosts: all
  gather_facts: false
  tasks:
    - name: Check NFS server service status
      systemd:
        name: nfs-server
        state: started
      register: nfs_service

    - name: Check if mount directory exists
      stat:
        path: "{{ SERVER_MNT_PATH }}"
      register: mnt_dir_existence

    - name: Display NFS service status
      meta: end_play
      when: nfs_service.status.ActiveState == 'active'and mnt_dir_existence.stat.exists

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: Install required packages
      apt:
        pkg:
          - nfs-kernel-server

      when: ansible_os_family == "Debian"

    - name: Create directory= mkdir -p
      ansible.builtin.file:
        path: "{{ SERVER_MNT_PATH }}"
        state: directory
        recurse: yes
        owner: nobody
        group: nogroup
        mode: '777'
    #### move to RelationshipType -  ConnectsToNFSServer
    # - name: Add new Line
    #   ansible.builtin.lineinfile:
    #     state: present
    #     dest: /etc/exports
    #     line: "{{ SERVER_MNT_PATH }} {{ item }}(rw,sync,no_subtree_check,no_root_squash)"
    #     # https://github.com/docker-library/postgres/issues/361
    #     insertafter: EOF
    #   loop:
    #     "{{ CLIENTS_IPS }}"

    # - name: export1 - 
    #   shell:
    #     cmd: "sudo exportfs -a"
        

    # - name: export2 - Restart nfs-kernel-server service
    #   ansible.builtin.service:
    #     name: nfs-kernel-server
    #     state: restarted