---
- hosts: localhost
  gather_facts: false

  vars:
    base_image: '{{BASE_WEBAPP_SERVER_NAME}}' # tomcat
    base_version: '{{ BASE_WEBAPP_SERVER_VERSION }}' # 9
    container_name: container_with_java_tomcat_repo
    image_namespace: '{{IMAGE_NAMESPACE}}' #igsrepo
    image_name: '{{IMAGE_NAME}}' #repository
    image_version: '{{ REPOSITORY_VERSION }}' # 1
    container_start_command: java -jar $CATALINA_BASE/webapps/app.jar
    my_app_path: '{{REPOSITORY_ARTIFACT}}'  #/home/ubuntu/opera-root/git-project/ma-jingyue2023/templates/igs_types/nodetypes/igs.nodes.ContainerApplication/igs.nodes.ContainerApplication.Repository/files/create/Artifacts/igsRepository.jar
    webserver_webapp_path: /var/lib/tomcat9/webapps/app.jar

  pre_tasks:

    # - name: Check for if this Docker image already exists
    #   community.docker.docker_image_info:
    #     name: '{{image_namespace}}/{{image_name}}:{{image_version}}'  
    #   register: image_info

    # - name: End play if the image exists
    #   meta: end_play
    #   when: image_info.images | length > 0

    - name: Check if image is available locally
      docker_image_info:
        name: '{{image_namespace}}/{{image_name}}:{{image_version}}'  
      register: local_image_info

    - name: Check for Docker image on Docker Hub
      uri:
        url: "https://hub.docker.com/v2/repositories/{{ image_namespace }}/{{ image_name }}/tags/{{ image_version }}/"
        method: GET
        return_content: yes
        status_code: 200,404
      register: docker_hub_image_response

    - name: Skip the rest of the tasks if image is found
      meta: end_play
      when: local_image_info.images|length > 0 or not docker_hub_image_response.status == 404

    - name: Start a container with tomcat base image
      community.docker.docker_container:
        name: '{{container_name}}'
        image: '{{image_namespace}}/{{base_image}}:{{base_version}}'
        command: sleep infinity
        state: started
        detach: true

    # - name: Add the newly created container to the inventory.
    #   add_host:
    #     hostname: '{{ container_name }}'
    #     ansible_connection: docker
    #     ansible_python_interpreter: /usr/bin/python3

    # - name: install Python to make ansible runnable in the container.
    #   raw: >
    #     apt-get update &&
    #     apt-get install -y --no-install-recommends python3
    #   changed_when: true
    #   delegate_to: '{{ container_name }}'


  tasks:
    # don't need to log into the container in this task
    - name: Copy my jar application into tomcat container
      community.docker.docker_container_copy_into:
        container: '{{container_name}}'
        path: '{{ my_app_path }}'
        container_path: '{{ webserver_webapp_path }}'

# docker cp {{ my_app_path }} {{container_name}}:{{ webserver_webapp_path }}

  post_tasks:
    # - name: Clean up the container's python.
    #   shell: |
    #     apt-get remove --purge -y python3
    #     rm -rf /var/lib/apt/lists/*
    #   changed_when: true
    #   delegate_to: '{{ container_name }}'

    - name: Commit the container.
      command: >
        docker commit
        -c 'CMD {{ container_start_command }}'
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:'{{image_version}}'
      changed_when: true
        
    - name: Remove the container.

      docker_container:
        name: '{{ container_name }}'
        state: absent

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{image_namespace}}/{{ image_name }}"
        tag: "{{ image_version }}"
        push: yes
        source: local