- name: Run Tomcat Docker Container with Default Webapp
  hosts: all
  gather_facts: no
  # http://192.168.221.163:8080/docs
  tasks:
    - name: Build Docker Image
      community.docker.docker_image:
        name: igs-proxy
        source: build
        tag: latest
        build:
          path: "."
          
    - name: Deploy stack - proxy
      community.docker.docker_stack:
        state: present
        name: igsstack
        compose:
          - version: '3'
            services:
              proxy:
                image: igs-proxy:latest
                ports:
                  - "80:80"
                ### dependency is expressed by Tosca ###
                # depends_on:
                #   - igsrepository
                #   - igsportal
                ########################################

